<?php

use App\App;

?>
<!-- FOOTER -->
<footer class="w-100 py-4 flex-shrink-0">
    <div class="container py-4">
        <div class="row gy-4 gx-5">
            <div class="col-lg-4 col-md-6">
                <h5 class="h1 text-white">Frise chronologique</h5>
                <p class="small text-muted">Le site à été crée dans le cadre d'un projet pour <span class="text-primary">lynn milard</span>.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel molestie metus, ut hendrerit quam. Donec dapibus nulla maximus justo.</p>
                <p class="small text-muted mb-0">&copy; Copyrights. Touts droits réservés.
                    <a class="text-primary" href="<?= App::getHost() ?>">lynnmilard.fr</a>
                </p>
            </div>
            <div class="col-lg-2 col-md-6">
                <h5 class="text-white mb-3">Liens rapides</h5>
                <ul class="list-unstyled text-muted">
                    <li><a href="<?= App::getHost() ?>">Frise</a></li>
                    <li><a href="<?= App::getHost() ?>/register">Inscription</a></li>
                    <li><a href="<?= App::getHost() ?>/login">Connexion</a></li>
                </ul>
            </div>
            <div class="col-lg-2 col-md-6">
                <h5 class="text-white mb-3">Réseaux</h5>
                <ul class="list-unstyled text-muted">
                    <li><a href="#">Instagram</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Youtube</a></li>
                </ul>
            </div>
            <div class="col-lg-4 col-md-6">
                <h5 class="text-white mb-3">Newsletter</h5>
                <p class="small text-muted">Vous pouvez vous abonner à notre newsletter pour ne rien louper de nos
                    prochaines mises à jour.</p>
                <form action="#">
                    <div class="input-group mb-3">
                        <input class="form-control" type="text" placeholder="Votre adresse mail"
                               aria-label="Votre adresse mail" aria-describedby="button-addon2">
                        <button class="btn btn-primary" id="button-addon2" type="button"><i
                                    class="fas fa-paper-plane"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</footer>