<?php

use App\App;

?>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <!-- Brand -->
    <a class="navbar-brand" href="#">
        <img width="50" src="<?= App::getHost() ?>/public/assets/logo/blogger.png" alt="logo"/>
    </a>

    <!-- Links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="<?= App::getHost() ?>">Accueil</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="<?= App::getHost() ?>/blog">Blog</a>
        </li>
    </ul>
</nav>