<?php
namespace App\Controllers;

use Core\Controllers\Controller;

/**
 * Class IndexController
 * @package App\Controllers
 */
class IndexController extends Controller
{
    public function beforeRender()
    {
        $this->setStylesheetPath('timeline.css');
        $this->setScriptPath('timeline.js');
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }
}