<?php
namespace App\Controllers;

use Core\Controllers\Controller;

/**
 * Class LoginController
 * @package App\Controller
 */
class LoginController extends Controller
{

    public function beforeRender()
    {
        $this->setStylesheetPath('login.css');
        $this->setScriptPath('login.js', true);
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

}